export { default as Home } from "./home/Home";
export { default as About } from "./about/About";
export { default as Business } from "./business/Business";
export { default as Personal } from "./personal/Personal";
export { default as Faq } from "./faq/Faq";
export { default as Complaint } from "./complaint/Complaint";
export { default as Contact } from "./contact/Contact";
export { default as Login } from "./login/Login";
export {default as Register} from "./register/Register";
export {default as Profile} from "./profile/Profile";
export {default as AnnualReport} from "./annual-report/AnnualReport";
export {default as PaypalScam} from "./paypal-scam/PaypalScam";